# Generated by Django 5.0.6 on 2026-06-18 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieCaveau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('largeur', models.DecimalField(decimal_places=2, max_digits=6)),
                ('longueur', models.DecimalField(decimal_places=2, max_digits=6)),
                ('prix_base', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Caveau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('reserve', 'Réservé'), ('occupe', 'Occupé'), ('non_exploitable', 'Non exploitable')], default='disponible', max_length=20)),
                ('latitude', models.FloatField(blank=True, help_text='Latitude GPS', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Longitude GPS', null=True)),
                ('section', models.CharField(max_length=10)),
                ('bloc', models.CharField(blank=True, max_length=10)),
                ('allee', models.CharField(blank=True, max_length=10)),
                ('superficie', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('historique_statut', models.JSONField(blank=True, default=list)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='terrains.categoriecaveau')),
            ],
        ),
    ]
