# Generated by Django 5.0.6 on 2026-06-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caveau',
            name='proprietaire_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='caveau',
            name='proprietaire_nom',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='categoriecaveau',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='caveau',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
