# Generated by Django 5.0.6 on 2026-06-18 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terrains', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('nom_defunt', models.CharField(max_length=200)),
                ('prenom_defunt', models.CharField(blank=True, max_length=200)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('date_deces', models.DateField()),
                ('date_enterrement', models.DateField()),
                ('nom_famille', models.CharField(blank=True, max_length=200)),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('caveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terrains.caveau')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
