# Generated by Django 5.0.6 on 2026-06-19 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
        ('terrains', '0002_caveau_proprietaire_contact_caveau_proprietaire_nom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='besoin_ceremonie',
            field=models.BooleanField(default=False, help_text="Besoin d'une cérémonie"),
        ),
        migrations.AddField(
            model_name='reservation',
            name='besoin_voiture',
            field=models.BooleanField(default=False, help_text='Besoin de voiture funéraire'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='certificat_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificats/'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='email_contact',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='reservation',
            name='facture_pdf',
            field=models.FileField(blank=True, null=True, upload_to='factures/'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_validees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='caveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='terrains.caveau'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('annulee', 'Annulée'), ('refusee', 'Refusée')], default='en_attente', max_length=20),
        ),
    ]
