# Generated by Django 5.0.6 on 2026-06-18 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_concession', models.CharField(choices=[('temporaire', 'Temporaire'), ('perpétuelle', 'Perpétuelle')], default='temporaire', max_length=20)),
                ('date_debut', models.DateField()),
                ('duree_ans', models.IntegerField(default=10, help_text='Durée en années (0 = perpétuelle)')),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('renouvelable', models.BooleanField(default=True)),
                ('date_renouvellement', models.DateField(blank=True, null=True)),
                ('contrat_pdf', models.FileField(blank=True, null=True, upload_to='concessions/contrats/')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Exhumation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('demande', 'Demande'), ('approuvee', 'Approuvée'), ('realisee', 'Réalisée'), ('refusee', 'Refusée')], default='demande', max_length=20)),
                ('motif', models.TextField()),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_approbation', models.DateTimeField(blank=True, null=True)),
                ('date_realisation', models.DateTimeField(blank=True, null=True)),
                ('autorisation_pdf', models.FileField(blank=True, null=True, upload_to='exhumations/autorisations/')),
                ('proces_verbal_pdf', models.FileField(blank=True, null=True, upload_to='exhumations/pv/')),
                ('concession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concessions.concession')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
