# Generated by Django 5.0.6 on 2026-06-19 09:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concessions', '0002_alter_concession_id_alter_exhumation_id'),
        ('reservations', '0002_reservation_besoin_ceremonie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='concession',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concession',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='concession',
            name='numero_contrat',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='exhumation',
            name='approuve_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhumations_approuvees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exhumation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='concession',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='concession', to='reservations.reservation'),
        ),
        migrations.AlterField(
            model_name='exhumation',
            name='concession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhumations', to='concessions.concession'),
        ),
    ]
