# Generated by Django 5.0.6 on 2026-06-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concessions', '0003_concession_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concession',
            name='duree_ans',
            field=models.IntegerField(default=10, help_text='Duree en annees (0 = perpetuelle)'),
        ),
        migrations.AlterField(
            model_name='concession',
            name='type_concession',
            field=models.CharField(choices=[('temporaire', 'Temporaire'), ('perpetuelle', 'Perpetuelle')], default='temporaire', max_length=20),
        ),
        migrations.AlterField(
            model_name='exhumation',
            name='statut',
            field=models.CharField(choices=[('demande', 'Demande'), ('approuvee', 'Approuvee'), ('realisee', 'Realisee'), ('refusee', 'Refusee')], default='demande', max_length=20),
        ),
    ]
