# Generated by Django 5.0.6 on 2026-06-19 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_alter_paiement_id'),
        ('reservations', '0002_reservation_besoin_ceremonie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='numero_telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='paiement',
            name='numero_transaction',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paiement',
            name='operateur',
            field=models.CharField(blank=True, help_text='Orange Money, Airtel Money, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='reservations.reservation'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='solde_restant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
