# Generated by Django 5.0.6 on 2026-06-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_paiement_notes_paiement_numero_telephone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='facture_generee_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='facture_pdf',
            field=models.FileField(blank=True, null=True, upload_to='factures/'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='methode',
            field=models.CharField(choices=[('airtel_money', 'Airtel Money'), ('mtn_money', 'MTN Mobile Money'), ('moov_money', 'Moov Money'), ('monex', 'Monex'), ('carte', 'Carte bancaire'), ('especes', 'Espèces'), ('virement', 'Virement')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='operateur',
            field=models.CharField(blank=True, help_text='Orange Money, Airtel Money, MTN Money, Moov Money, etc.', max_length=50),
        ),
    ]
